# Site settings
title: Emre Kaan's Website
description: Emre Kaan's personal blog
# url: "brendev.co"
permalink: pretty

# Sass
sass:
    sass_dir: _sass

# Navigation Bar
# navigation-header:
#   Home: /
#   Posts: /posts/
#   Categories: /Categories/
#   Projects: /projects/

# User settings
username: Emre Kaan Ozkan
user_title: Electronics And Communication Engineer
email: emrekaanozkan@outlook.com

exclude: ['package.json', 'src' , 'node_modules']
